# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GitCommits' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GitCommits
  pod 'Alamofire'
  
  target 'GitCommitsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GitCommitsUITests' do
    # Pods for testing
  end

end
